name: Lint

on: [push]

jobs:
  python-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pycodestyle
    - name: Analysing the code with pycodestyle (pep8)
      run: |
        pycodestyle .
